/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Change Credentials */
        put: operations["change_credentials_v1_auth_credentials_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Setup */
        post: operations["setup_v1_auth_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Auth Status */
        get: operations["auth_status_v1_auth_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List History */
        get: operations["list_history_v1_history_get"];
        put?: never;
        post?: never;
        /** Clear History */
        delete: operations["clear_history_v1_history_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/history/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Operation */
        get: operations["get_operation_v1_history__operation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Media
         * @description Queue an import and return immediately; the worker picks it up.
         *
         *     Idempotent on ``job_id`` so the shim can retry a submission whose reply was
         *     lost without queueing the mux twice.
         */
        post: operations["import_media_v1_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Recent jobs, log included: the only view of one that never reached the history.
         */
        get: operations["list_jobs_v1_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Detail
         * @description The same job with its captured log, for the UI to poll while it runs.
         */
        get: operations["get_job_detail_v1_jobs__job_id__detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{job_id}/protocol": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Protocol
         * @description Long-poll transport for the shim, rendered as *arr's stdout protocol.
         *
         *     Always 200, with the state in the body: curl and busybox wget surface non-2xx
         *     so differently that a sh shim cannot tell "unknown job" from "connection
         *     refused". Encoding state in the body makes a missing state line mean exactly
         *     one thing -- transport failure, worth retrying.
         */
        get: operations["get_job_protocol_v1_jobs__job_id__protocol_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Settings */
        get: operations["read_settings_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Settings */
        patch: operations["update_settings_v1_settings_patch"];
        trace?: never;
    };
    "/v1/settings/ai/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Probe Ai Provider */
        post: operations["probe_ai_provider_v1_settings_ai_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Api Key */
        get: operations["read_api_key_v1_settings_api_key_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/settings/api-key/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate Api Key */
        post: operations["regenerate_api_key_v1_settings_api_key_regenerate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_v1_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get System */
        get: operations["get_system_v1_system_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AiTestRequest
         * @description Credentials as currently typed, so a key can be checked before saving.
         */
        AiTestRequest: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url: string;
            /** Model */
            model: string;
            /**
             * Timeout Seconds
             * @default 10
             */
            timeout_seconds: number;
        };
        /** AiTestResult */
        AiTestResult: {
            /** Latency Ms */
            latency_ms: number;
            /** Message */
            message: string;
            /** Ok */
            ok: boolean;
        };
        /** ApiKeyView */
        ApiKeyView: {
            /** Api Key */
            api_key: string;
            /** Locked */
            locked: boolean;
        };
        /** ArrModel */
        ArrModel: {
            /** Instance */
            instance: string;
            /** Link */
            link: string | null;
            /** Original Language */
            original_language: string | null;
            /** Tags */
            tags: string[];
            /** Title */
            title: string;
            /** Year */
            year: number | null;
        };
        /**
         * ArrPayload
         * @description As the shim sends it: every value a string, straight from the environment.
         *
         *     Lenient on purpose. A value that fails validation here would 422 the whole
         *     import and delay *arr for a minute of retries, over a detail that is only
         *     ever informational or an input to an optional rule.
         */
        ArrPayload: {
            /**
             * Instance
             * @default
             */
            instance: string;
            /**
             * Original Language
             * @default
             */
            original_language: string;
            /**
             * Slug
             * @default
             */
            slug: string;
            /**
             * Tags
             * @default
             */
            tags: string;
            /**
             * Title
             * @default
             */
            title: string;
            /**
             * Url
             * @default
             */
            url: string;
            /**
             * Year
             * @default
             */
            year: string;
        };
        /** AuthStatusView */
        AuthStatusView: {
            /** Authenticated */
            authenticated: boolean;
            /** Credentials Locked */
            credentials_locked: boolean;
            /**
             * Method
             * @enum {string}
             */
            method: "forms" | "external";
            /**
             * Required
             * @enum {string}
             */
            required: "enabled" | "disabled_for_local_addresses";
            /** Setup Required */
            setup_required: boolean;
            /** Username */
            username: string | null;
        };
        /** ClearedModel */
        ClearedModel: {
            /** Deleted */
            deleted: number;
        };
        /** Credentials */
        Credentials: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** CredentialsChange */
        CredentialsChange: {
            /** Current Password */
            current_password: string;
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Read Roots */
            read_roots: string[];
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /** Version */
            version: string;
            /**
             * Worker Alive
             * @default false
             */
            worker_alive: boolean;
            /** Worker Seen At */
            worker_seen_at: string | null;
        };
        /** HealthIssueModel */
        HealthIssueModel: {
            /**
             * Code
             * @enum {string}
             */
            code: "worker_offline" | "mkvmerge_missing" | "mkvmerge_outdated" | "read_root_missing" | "read_root_unreadable" | "scratch_dir_unusable" | "sqlite_split" | "login_off" | "proxies_untrusted";
            /**
             * Level
             * @enum {string}
             */
            level: "notice" | "warning" | "error";
            /** Message */
            message: string;
        };
        /** HistoryPage */
        HistoryPage: {
            /** Items */
            items: components["schemas"]["OperationModel"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** ImportPayload */
        ImportPayload: {
            /**
             * App
             * @enum {string}
             */
            app: "radarr" | "sonarr";
            arr?: components["schemas"]["ArrPayload"] | null;
            /** Destination Path */
            destination_path: string;
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
            /** Job Id */
            job_id: string;
            /** Source Path */
            source_path: string;
            /**
             * Transfer Mode
             * @default Move
             */
            transfer_mode: string;
        };
        /** ImportResult */
        ImportResult: {
            /** Added Tracks */
            added_tracks: components["schemas"]["TrackModel"][];
            /** Extra Files */
            extra_files: string[];
            /** Media File */
            media_file: string | null;
            /**
             * Move Status
             * @enum {string}
             */
            move_status: "DeferMove" | "MoveComplete" | "RenameRequested";
            /**
             * Prevent Extra Import
             * @default false
             */
            prevent_extra_import: boolean;
            /** Reason */
            reason: string;
            /** Rejected Tracks */
            rejected_tracks: components["schemas"]["RejectedTrackModel"][];
            /** Removed Tracks */
            removed_tracks: components["schemas"]["RemovedTrackModel"][];
        };
        /**
         * JobDetailModel
         * @description A job as the UI watches it, log included.
         *
         *     Separate from :class:`JobModel` so the shim's reply stays as small as it has
         *     always been -- it polls this route on a loop and cares about four fields.
         */
        JobDetailModel: {
            /**
             * App
             * @enum {string}
             */
            app: "radarr" | "sonarr";
            arr: components["schemas"]["ArrModel"] | null;
            /** Created At */
            created_at: string;
            /** Destination Path */
            destination_path: string;
            /** Dry Run */
            dry_run: boolean;
            /** Error */
            error: string | null;
            /** History Id */
            history_id: number | null;
            /** Id */
            id: string;
            /** Log */
            log: components["schemas"]["LogEntryModel"][];
            result: components["schemas"]["ImportResult"] | null;
            /** Source Path */
            source_path: string;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "succeeded" | "failed";
            /** Title */
            title: string;
            /** Transfer Mode */
            transfer_mode: string;
            /** Updated At */
            updated_at: string;
        };
        /** JobModel */
        JobModel: {
            /** Error */
            error: string | null;
            /** History Id */
            history_id: number | null;
            /** Id */
            id: string;
            result: components["schemas"]["ImportResult"] | null;
            /**
             * State
             * @enum {string}
             */
            state: "pending" | "running" | "succeeded" | "failed";
        };
        /** JobPageModel */
        JobPageModel: {
            /** Items */
            items: components["schemas"]["JobDetailModel"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** LogEntryModel */
        LogEntryModel: {
            /** Component */
            component: string;
            /** Context */
            context: {
                [key: string]: string;
            };
            /** Level */
            level: string;
            /** Message */
            message: string;
            stage: components["schemas"]["LogStage"] | null;
            /** Ts */
            ts: string;
        };
        /**
         * LogStage
         * @description The step of an import a log record belongs to.
         *
         *     Closed, because the UI renders one timeline item per stage and an unknown
         *     value would simply vanish from it.
         * @enum {string}
         */
        LogStage: "guard" | "probe" | "discovery" | "ai" | "selection" | "mux" | "placement" | "outcome";
        /** OperationModel */
        OperationModel: {
            /** Added Tracks */
            added_tracks: components["schemas"]["TrackModel"][];
            /**
             * App
             * @enum {string}
             */
            app: "radarr" | "sonarr";
            arr: components["schemas"]["ArrModel"] | null;
            /** Created At */
            created_at: string;
            /** Destination Path */
            destination_path: string;
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
            /**
             * Duration Ms
             * @default 0
             */
            duration_ms: number;
            /** Episodes */
            episodes: number[];
            /** Id */
            id: number;
            /** Log */
            log: components["schemas"]["LogEntryModel"][];
            /** Media File */
            media_file: string | null;
            /**
             * Move Status
             * @enum {string}
             */
            move_status: "DeferMove" | "MoveComplete" | "RenameRequested";
            /** Output Bytes */
            output_bytes: number | null;
            /** Reason */
            reason: string;
            /** Rejected Tracks */
            rejected_tracks: components["schemas"]["RejectedTrackModel"][];
            /** Removed Tracks */
            removed_tracks: components["schemas"]["RemovedTrackModel"][];
            /** Season */
            season: number | null;
            /** Source Bytes */
            source_bytes: number | null;
            /** Source Path */
            source_path: string;
            /** Title */
            title: string;
            /**
             * Transfer Mode
             * @default
             */
            transfer_mode: string;
        };
        /** QueueStatusModel */
        QueueStatusModel: {
            /** Failed */
            failed: number;
            /** Pending */
            pending: number;
            /** Running */
            running: number;
            /** Succeeded */
            succeeded: number;
        };
        /** RejectedTrackModel */
        RejectedTrackModel: {
            /** Code */
            code: ("image_subtitle" | "undetermined_language" | "language_not_kept" | "already_present" | "track_limit" | "file_missing" | "file_empty" | "uninspectable" | "no_tracks") | null;
            /**
             * Kind
             * @default subtitles
             * @enum {string}
             */
            kind: "video" | "audio" | "subtitles";
            /**
             * Language
             * @default und
             */
            language: string;
            /** Reason */
            reason: string;
            /**
             * Source
             * @default heuristic
             * @enum {string}
             */
            source: "heuristic" | "ai";
            /** Track */
            track: string;
        };
        /** RemovedTrackModel */
        RemovedTrackModel: {
            /**
             * Codec
             * @default
             */
            codec: string;
            /**
             * Forced
             * @default false
             */
            forced: boolean;
            /** Index */
            index: number;
            /**
             * Kind
             * @default subtitles
             * @enum {string}
             */
            kind: "video" | "audio" | "subtitles";
            /**
             * Language
             * @default und
             */
            language: string;
            /** Name */
            name: string | null;
            /**
             * Reason
             * @default
             */
            reason: string;
        };
        /**
         * SettingsPatch
         * @description Only the fields actually sent are changed.
         */
        SettingsPatch: {
            /** Ai Api Key */
            ai_api_key?: string | null;
            /** Ai Base Url */
            ai_base_url?: string | null;
            /** Ai Max Entries */
            ai_max_entries?: number | null;
            /** Ai Mode */
            ai_mode?: ("off" | "fallback" | "always" | "verify") | null;
            /** Ai Model */
            ai_model?: string | null;
            /** Ai Name Tracks */
            ai_name_tracks?: boolean | null;
            /** Ai Timeout Seconds */
            ai_timeout_seconds?: number | null;
            /** Auth Required */
            auth_required?: ("enabled" | "disabled_for_local_addresses") | null;
            /** Dedupe */
            dedupe?: ("off" | "language" | "language_codec") | null;
            /** Free Space Factor */
            free_space_factor?: number | null;
            /** History Max Records */
            history_max_records?: number | null;
            /** Job Ttl Seconds */
            job_ttl_seconds?: number | null;
            /** Keep Audio Languages */
            keep_audio_languages?: string[] | null;
            /** Keep Subtitle Languages */
            keep_subtitle_languages?: string[] | null;
            /** Log Level */
            log_level?: ("TRACE" | "DEBUG" | "INFO" | "SUCCESS" | "WARNING" | "ERROR" | "CRITICAL") | null;
            /** Max Concurrent Muxes */
            max_concurrent_muxes?: number | null;
            /** Max External Tracks */
            max_external_tracks?: number | null;
            /** Mux Timeout Seconds */
            mux_timeout_seconds?: number | null;
            /** Operation Log Max Entries */
            operation_log_max_entries?: number | null;
            /** Preserve Ownership */
            preserve_ownership?: boolean | null;
            /** Require Tags */
            require_tags?: string[] | null;
            /** Skip Image Subtitles */
            skip_image_subtitles?: boolean | null;
            /** Skip Tags */
            skip_tags?: string[] | null;
            /** Skip Undetermined Language */
            skip_undetermined_language?: boolean | null;
            /** Sub Charset */
            sub_charset?: string | null;
        };
        /** SettingsView */
        SettingsView: {
            /** Ai Api Key Set */
            ai_api_key_set: boolean;
            /** Ai Base Url */
            ai_base_url: string;
            /** Ai Max Entries */
            ai_max_entries: number;
            /**
             * Ai Mode
             * @enum {string}
             */
            ai_mode: "off" | "fallback" | "always" | "verify";
            /** Ai Model */
            ai_model: string;
            /** Ai Name Tracks */
            ai_name_tracks: boolean;
            /** Ai Timeout Seconds */
            ai_timeout_seconds: number;
            /**
             * Auth Method
             * @enum {string}
             */
            auth_method: "forms" | "external";
            /**
             * Auth Required
             * @enum {string}
             */
            auth_required: "enabled" | "disabled_for_local_addresses";
            /**
             * Dedupe
             * @enum {string}
             */
            dedupe: "off" | "language" | "language_codec";
            /** Free Space Factor */
            free_space_factor: number;
            /** History Max Records */
            history_max_records: number;
            /** Job Ttl Seconds */
            job_ttl_seconds: number;
            /** Keep Audio Languages */
            keep_audio_languages: string[];
            /** Keep Subtitle Languages */
            keep_subtitle_languages: string[];
            /** Locked */
            locked: string[];
            /** Log Level */
            log_level: string;
            /** Max Concurrent Muxes */
            max_concurrent_muxes: number;
            /** Max External Tracks */
            max_external_tracks: number;
            /** Mux Timeout Seconds */
            mux_timeout_seconds: number;
            /** Operation Log Max Entries */
            operation_log_max_entries: number;
            /** Preserve Ownership */
            preserve_ownership: boolean;
            /** Require Tags */
            require_tags: string[];
            /** Skip Image Subtitles */
            skip_image_subtitles: boolean;
            /** Skip Tags */
            skip_tags: string[];
            /** Skip Undetermined Language */
            skip_undetermined_language: boolean;
            /** Sub Charset */
            sub_charset: string | null;
        };
        /** StatsModel */
        StatsModel: {
            /** Deferred */
            deferred: number;
            /** Last 24H */
            last_24h: number;
            /** Muxed */
            muxed: number;
            /** Total */
            total: number;
            /** Tracks Added */
            tracks_added: number;
        };
        /** SystemStatus */
        SystemStatus: {
            /** Health */
            health: components["schemas"]["HealthIssueModel"][];
            queue: components["schemas"]["QueueStatusModel"];
            /** Version */
            version: string;
            worker: components["schemas"]["WorkerStatusModel"];
        };
        /** TrackModel */
        TrackModel: {
            /**
             * File
             * @default
             */
            file: string;
            /**
             * Forced
             * @default false
             */
            forced: boolean;
            /**
             * Hearing Impaired
             * @default false
             */
            hearing_impaired: boolean;
            /**
             * Kind
             * @default subtitles
             * @enum {string}
             */
            kind: "video" | "audio" | "subtitles";
            /**
             * Label
             * @default
             */
            label: string;
            /**
             * Language
             * @default und
             */
            language: string;
            /** Name */
            name: string | null;
            /**
             * Source
             * @default heuristic
             * @enum {string}
             */
            source: "heuristic" | "ai";
            /** Variant */
            variant: string | null;
        };
        /** UserView */
        UserView: {
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkerStatusModel */
        WorkerStatusModel: {
            /** Alive */
            alive: boolean;
            /** Last Seen At */
            last_seen_at: string | null;
            /** Max Concurrent Muxes */
            max_concurrent_muxes: number;
            /** Stale After Seconds */
            stale_after_seconds: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    change_credentials_v1_auth_credentials_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CredentialsChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatusView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setup_v1_auth_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatusView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    auth_status_v1_auth_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthStatusView"];
                };
            };
        };
    };
    list_history_v1_history_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                move_status?: string | null;
                app?: string | null;
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_history_v1_history_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClearedModel"];
                };
            };
        };
    };
    get_operation_v1_history__operation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_media_v1_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_v1_jobs_get: {
        parameters: {
            query?: {
                state?: ("pending" | "running" | "succeeded" | "failed") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobPageModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_v1_jobs__job_id__get: {
        parameters: {
            query?: {
                wait?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_detail_v1_jobs__job_id__detail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetailModel"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_protocol_v1_jobs__job_id__protocol_get: {
        parameters: {
            query?: {
                wait?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_settings_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsView"];
                };
            };
        };
    };
    update_settings_v1_settings_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    probe_ai_provider_v1_settings_ai_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AiTestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AiTestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_api_key_v1_settings_api_key_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyView"];
                };
            };
        };
    };
    regenerate_api_key_v1_settings_api_key_regenerate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyView"];
                };
            };
        };
    };
    get_stats_v1_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsModel"];
                };
            };
        };
    };
    get_system_v1_system_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
}
