"""create operations table

Revision ID: e919baae3319
Revises: 
Create Date: 2026-09-21 16:47:41.048786
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'e919baae3319'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('app', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('move_status', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('destination_path', sa.Text(), nullable=False),
    sa.Column('media_file', sa.Text(), nullable=True),
    sa.Column('transfer_mode', sa.Text(), server_default='', nullable=False),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('episodes', sa.Text(), server_default='', nullable=False),
    sa.Column('added_tracks', sa.Text(), server_default='[]', nullable=False),
    sa.Column('rejected_tracks', sa.Text(), server_default='[]', nullable=False),
    sa.Column('duration_ms', sa.Integer(), server_default='0', nullable=False),
    sa.Column('source_bytes', sa.Integer(), nullable=True),
    sa.Column('output_bytes', sa.Integer(), nullable=True),
    sa.Column('dry_run', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.create_index('idx_operations_app', ['app'], unique=False)
        batch_op.create_index('idx_operations_created', ['created_at'], unique=False)
        batch_op.create_index('idx_operations_status', ['move_status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operations', schema=None) as batch_op:
        batch_op.drop_index('idx_operations_status')
        batch_op.drop_index('idx_operations_created')
        batch_op.drop_index('idx_operations_app')

    op.drop_table('operations')
    # ### end Alembic commands ###
