"""add jobs and worker state

Revision ID: fd2e776bb383
Revises: e919baae3319
Create Date: 2026-09-21 20:30:10.401645
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = 'fd2e776bb383'
down_revision: str | None = 'e919baae3319'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('fingerprint', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), server_default='pending', nullable=False),
    sa.Column('app', sa.Text(), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=False),
    sa.Column('destination_path', sa.Text(), nullable=False),
    sa.Column('transfer_mode', sa.Text(), server_default='Move', nullable=False),
    sa.Column('dry_run', sa.Integer(), server_default='0', nullable=False),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('history_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('idx_jobs_state_created', ['state', 'created_at'], unique=False)

    op.create_table('worker_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_state')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('idx_jobs_state_created')

    op.drop_table('jobs')
    # ### end Alembic commands ###
